version: "2"
plugins:
  brakeman:
    enabled: true
    config:
      app_path:
        - "api/"
        - "core/"
        - "emails/"
      skip_files: "api/app/controllers/spree/api/v1"
  rubocop:
    enabled: true
    checks:
      Rubocop/Naming/RescuedExceptionsVariableName:
        enabled: false
      Rubocop/Layout/AlignArguments:
        enabled: false
      Rubocop/Style/MultilineWhenThen:
        enabled: false
      Rubocop/Layout/SpaceAroundOperators:
        enabled: false
      Rubocop/Style/FormatStringToken:
        enabled: false
    config:
      file: .rubocop.yml
    channel: "rubocop-1-10-0"
exclude_patterns:
  - "**/bin/"
  - "**/script/"
  - "**/vendor/"
  - "**/spec/"
  - "public/"
  - "sample/db/samples"
