before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "bundle exec rake test_app"
  - "cd api; bundle install; bundle exec rspec spec"
  - "cd ../auth; bundle install; bundle exec rspec spec"
  - "cd ../core; bundle install; bundle exec rspec spec"
  - "cd ../dash; bundle install; bundle exec rspec spec"
  - "cd ../promo; bundle install; bundle exec rspec spec"

notifications:
  email:
    - ryan@spreecommerce.com
  irc: "irc.freenode.org#spree"
branches:
  only:
    - 1-0-stable
    - master
    - isolation
rvm:
  - 1.8.7
  - 1.9.3
