steps:
  - name: Test Container
    command: |
      if ! docker pull "$TEST_CONTAINER" &> /dev/null; then
        docker build --tag "$TEST_CONTAINER" -- .
        docker push "$TEST_CONTAINER"
      fi
    agents:
      queue: mrh-build

  - wait

  - name: API Model Tests
    command: |
      docker-wrapper --path api --database -- bash -c '
        ../scripts/setup-ci.sh api
        bundle exec rake metrics:coverage
      '
    agents:
      queue: mrh-build

  - name: API Rubocop
    command: |
      docker-wrapper --path api -- bash -c '
        ../scripts/setup-ci.sh api
        bundle exec rake metrics:rubocop
      '
    agents:
      queue: mrh-build

  - name: API Reek
    command: |
      docker-wrapper --path api -- bash -c '
        ../scripts/setup-ci.sh api
        bundle exec rake metrics:reek
      '
    agents:
      queue: mrh-build

  - name: API Flay
    command: |
      docker-wrapper --path api -- bash -c '
        ../scripts/setup-ci.sh api
        bundle exec rake metrics:flay
      '
    agents:
      queue: mrh-build

  - name: API Flog
    command: |
      docker-wrapper --path api -- bash -c '
        ../scripts/setup-ci.sh api
        bundle exec rake metrics:flog
      '
    agents:
      queue: mrh-build

  - name: API Yardstick
    command: |
      docker-wrapper --path api -- bash -c '
        ../scripts/setup-ci.sh api
        bundle exec rake metrics:yardstick:verify
      '
    agents:
      queue: mrh-build

  - name: Backend Model Tests
    command: |
      docker-wrapper --path backend --database -- bash -c '
        ../scripts/setup-ci.sh backend
        bundle exec rake metrics:coverage
      '
    agents:
      queue: mrh-build

  - name: Backend Rubocop
    command: |
      docker-wrapper --path backend -- bash -c '
        ../scripts/setup-ci.sh backend
        bundle exec rake metrics:rubocop
      '
    agents:
      queue: mrh-build

  - name: Backend Reek
    command: |
      docker-wrapper --path backend -- bash -c '
        ../scripts/setup-ci.sh backend
        bundle exec rake metrics:reek
      '
    agents:
      queue: mrh-build

  - name: Backend Flay
    command: |
      docker-wrapper --path backend -- bash -c '
        ../scripts/setup-ci.sh backend
        bundle exec rake metrics:flay
      '
    agents:
      queue: mrh-build

  - name: Backend Flog
    command: |
      docker-wrapper --path backend -- bash -c '
        ../scripts/setup-ci.sh backend 
        bundle exec rake metrics:flog
      '
    agents:
      queue: mrh-build

  - name: Backend Yardstick
    command: |
      docker-wrapper --path backend -- bash -c '
        ../scripts/setup-ci.sh backend 
        bundle exec rake metrics:yardstick:verify
      '
    agents:
      queue: mrh-build

  - name: Core Model Tests
    command: |
      docker-wrapper --path core --database -- bash -c '
        ../scripts/setup-ci.sh core
        bundle exec rake metrics:coverage
      '
    agents:
      queue: mrh-build

  - name: Core Rubocop
    command: |
      docker-wrapper --path core -- bash -c '
        ../scripts/setup-ci.sh core
        bundle exec rake metrics:rubocop
      '
    agents:
      queue: mrh-build

  - name: Core Reek
    command: |
      docker-wrapper --path core -- bash -c '
        ../scripts/setup-ci.sh core
        bundle exec rake metrics:reek
      '
    agents:
      queue: mrh-build

  - name: Core Flay
    command: |
      docker-wrapper --path core -- bash -c '
        ../scripts/setup-ci.sh core
        bundle exec rake metrics:flay
      '
    agents:
      queue: mrh-build

  - name: Core Flog
    command: |
      docker-wrapper --path core -- bash -c '
        ../scripts/setup-ci.sh core
        bundle exec rake metrics:flog
      '
    agents:
      queue: mrh-build

  - name: Core Yardstick
    command: |
      docker-wrapper --path core -- bash -c '
        ../scripts/setup-ci.sh core
        bundle exec rake metrics:yardstick:verify
      '
    agents:
      queue: mrh-build

  - name: Frontend Model Tests
    command: |
      docker-wrapper --path frontend --database -- bash -c '
        ../scripts/setup-ci.sh frontend
        bundle exec rake metrics:coverage
      '
    agents:
      queue: mrh-build

  - name: Frontend Rubocop
    command: |
      docker-wrapper --path frontend -- bash -c '
        ../scripts/setup-ci.sh frontend
        bundle exec rake metrics:rubocop
      '
    agents:
      queue: mrh-build

  - name: Frontend Reek
    command: |
      docker-wrapper --path frontend -- bash -c '
        ../scripts/setup-ci.sh frontend
        bundle exec rake metrics:reek
      '
    agents:
      queue: mrh-build

  - name: Frontend Flay
    command: |
      docker-wrapper --path frontend -- bash -c '
        ../scripts/setup-ci.sh frontend
        bundle exec rake metrics:flay
      '
    agents:
      queue: mrh-build

  - name: Frontend Flog
    command: |
      docker-wrapper --path frontend -- bash -c '
        ../scripts/setup-ci.sh frontend
        bundle exec rake metrics:flog
      '
    agents:
      queue: mrh-build

  - name: Frontend Yardstick
    command: |
      docker-wrapper --path frontend -- bash -c '
        ../scripts/setup-ci.sh frontend
        bundle exec rake metrics:yardstick:verify
      '
    agents:
      queue: mrh-build
