env:
  BASE_CONTAINER: 207654339136.dkr.ecr.us-east-1.amazonaws.com/mountainroseherbs/spree-test:$PREVIOUS_SHA
  TEST_CONTAINER: 207654339136.dkr.ecr.us-east-1.amazonaws.com/mountainroseherbs/spree-test:$COMMIT_SHA

steps:
  - name: Test Container
    command: |
      set -e
      eval "$(aws ecr get-login)"
      docker pull "$BASE_CONTAINER" || true
      docker build --tag "$TEST_CONTAINER" -- .
      docker push "$TEST_CONTAINER"
    agents:
      queue: mrh-build

  - wait

  - name: API Model Tests
    command: docker-bundle-exec --path api --database -- rake metrics:coverage
    agents:
      queue: mrh-build

  - name: API Rubocop
    command: docker-bundle-exec --path api -- rake metrics:rubocop
    agents:
      queue: mrh-build

  - name: API Reek
    command: docker-bundle-exec --path api -- rake metrics:reek
    agents:
      queue: mrh-build

  - name: API Flay
    command: docker-bundle-exec --path api -- rake metrics:flay
    agents:
      queue: mrh-build

  - name: API Flog
    command: docker-bundle-exec --path api -- rake metrics:flog
    agents:
      queue: mrh-build

  - name: API Yardstick
    command: docker-bundle-exec --path api -- rake metrics:yardstick:verify
    agents:
      queue: mrh-build

  - name: Backend Model Tests
    command: docker-bundle-exec --path backend --database -- rake metrics:coverage
    agents:
      queue: mrh-build

  - name: Backend Rubocop
    command: docker-bundle-exec --path backend -- rake metrics:rubocop
    agents:
      queue: mrh-build

  - name: Backend Reek
    command: docker-bundle-exec --path backend -- rake metrics:reek
    agents:
      queue: mrh-build

  - name: Backend Flay
    command: docker-bundle-exec --path backend -- rake metrics:flay
    agents:
      queue: mrh-build

  - name: Backend Flog
    command: docker-bundle-exec --path backend -- rake metrics:flog
    agents:
      queue: mrh-build

  - name: Backend Yardstick
    command: docker-bundle-exec --path backend -- rake metrics:yardstick:verify
    agents:
      queue: mrh-build

  - name: Core Model Tests
    command: docker-bundle-exec --path core --database -- rake metrics:coverage
    agents:
      queue: mrh-build

  - name: Core Rubocop
    command: docker-bundle-exec --path core -- rake metrics:rubocop
    agents:
      queue: mrh-build

  - name: Core Reek
    command: docker-bundle-exec --path core -- rake metrics:reek
    agents:
      queue: mrh-build

  - name: Core Flay
    command: docker-bundle-exec --path core -- rake metrics:flay
    agents:
      queue: mrh-build

  - name: Core Flog
    command: docker-bundle-exec --path core -- rake metrics:flog
    agents:
      queue: mrh-build

  - name: Core Yardstick
    command: docker-bundle-exec --path core -- rake metrics:yardstick:verify
    agents:
      queue: mrh-build

  - name: Frontend Model Tests
    command: docker-bundle-exec --path frontend --database -- rake metrics:coverage
    agents:
      queue: mrh-build

  - name: Frontend Rubocop
    command: docker-bundle-exec --path frontend -- rake metrics:rubocop
    agents:
      queue: mrh-build

  - name: Frontend Reek
    command: docker-bundle-exec --path frontend -- rake metrics:reek
    agents:
      queue: mrh-build

  - name: Frontend Flay
    command: docker-bundle-exec --path frontend -- rake metrics:flay
    agents:
      queue: mrh-build

  - name: Frontend Flog
    command: docker-bundle-exec --path frontend -- rake metrics:flog
    agents:
      queue: mrh-build

  - name: Frontend Yardstick
    command: docker-bundle-exec --path frontend -- rake metrics:yardstick:verify
    agents:
      queue: mrh-build
