---
Attribute:
  enabled: true
  exclude:
  - Spree::Api::BaseController#current_api_user # writable attribute
BooleanParameter:
  enabled: true
  exclude:
  - Spree::Api::OrdersController#find_order # `lock` param
  - Spree::Api::CheckoutsController#load_order # `lock` param
ClassVariable:
  enabled: false
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  max_copies: 1
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
  - Spree::Api::OrdersController#normalize_params # 15 calls to params[:order]
  - Spree::Api::StockItemsController#update # 4 calls to params[:stock_item]
  max_calls: 2
  allow_calls: []
FeatureEnvy:
  enabled: false
  exclude: []
IrresponsibleModule:
  enabled: false
  exclude: []
LongParameterList:
  enabled: true
  exclude: []
  max_params: 2
  overrides:
    initialize:
      max_params: 3
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
ModuleInitialize:
  enabled: false
NestedIterators:
  enabled: true
  exclude: []
  max_allowed_nesting: 2
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude:
  - Spree::Api::TaxonsController#create
PrimaDonnaMethod:
  enabled: true
  exclude:
  - Spree::Api::BaseController # invalid_resource!
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 2
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Spree::Api::ShipmentsController # 8 ivars
  max_instance_variables: 4
TooManyMethods:
  enabled: true
  exclude:
  - Spree::Api::BaseController # 23 methods
TooManyStatements:
  enabled: true
  exclude: []
  max_statements: 9
UncommunicativeMethodName:
  enabled: false
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: false
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Spree::Api::BaseController#current_currency
  - Spree::Api::BaseController#map_nested_attributes_keys
  - Spree::Api::BaseController#requires_authentication?
  - Spree::Api::ApiHelpers#required_fields_for
  - Spree::Api::TestingSupport::Helpers#image
